#!/usr/bin/env bash
# Test suite for outputs/dotenv.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

source "$REPO_ROOT/outputs/dotenv.sh"

PASS=0
FAIL=0
TMPDIR_TEST=""

setup() {
    TMPDIR_TEST=$(mktemp -d)
}

teardown() {
    [[ -n "$TMPDIR_TEST" ]] && rm -rf "$TMPDIR_TEST"
}

assert_eq() {
    local test_name="$1" expected="$2" actual="$3"
    if [[ "$expected" == "$actual" ]]; then
        echo "  PASS: $test_name"
        PASS=$((PASS + 1))
    else
        echo "  FAIL: $test_name"
        echo "    expected: $expected"
        echo "    actual:   $actual"
        FAIL=$((FAIL + 1))
    fi
}

assert_exit_code() {
    local test_name="$1" expected_code="$2"
    shift 2
    local actual_code=0
    "$@" >/dev/null 2>&1 || actual_code=$?
    if [[ "$expected_code" == "$actual_code" ]]; then
        echo "  PASS: $test_name"
        PASS=$((PASS + 1))
    else
        echo "  FAIL: $test_name"
        echo "    expected exit code: $expected_code"
        echo "    actual exit code:   $actual_code"
        FAIL=$((FAIL + 1))
    fi
}

trap teardown EXIT
setup

echo "=== Dotenv Output Tests ==="
echo ""

# Test 1: basic dotenv generation
echo "Test 1: basic .env generation"
outfile="$TMPDIR_TEST/.env.sit"
secrets_json='[{"name":"client_secret_td","value":"abc123"},{"name":"baseurl","value":"https://example.com"}]'
output_dotenv_generate "td-postman" "sit" "$outfile" "$secrets_json"
assert_eq "output file exists" "true" "$([ -f "$outfile" ] && echo true || echo false)"

# Test 2: header comments
echo "Test 2: header comments"
line1=$(sed -n '1p' "$outfile")
assert_eq "generated comment" "# Generated by secrets-bridge - do not edit" "$line1"
line2=$(sed -n '2p' "$outfile")
assert_eq "environment comment" "# Environment: sit" "$line2"

# Test 3: key-value pairs with uppercase conversion
echo "Test 3: key-value pairs"
line3=$(sed -n '3p' "$outfile")
assert_eq "first entry uppercase" "CLIENT_SECRET_TD=abc123" "$line3"
line4=$(sed -n '4p' "$outfile")
assert_eq "second entry" "BASEURL=https://example.com" "$line4"

# Test 4: values with spaces are quoted
echo "Test 4: values with spaces are quoted"
outfile2="$TMPDIR_TEST/.env.test"
secrets_json2='[{"name":"my-key","value":"hello world"},{"name":"simple","value":"nospaceshere"}]'
output_dotenv_generate "test" "dev" "$outfile2" "$secrets_json2"
line3=$(sed -n '3p' "$outfile2")
assert_eq "quoted value with spaces" 'MY_KEY="hello world"' "$line3"
line4=$(sed -n '4p' "$outfile2")
assert_eq "unquoted simple value" "SIMPLE=nospaceshere" "$line4"

# Test 5: hyphenated names become underscored
echo "Test 5: hyphen to underscore"
outfile3="$TMPDIR_TEST/.env.hyphen"
secrets_json3='[{"name":"my-api-key","value":"val123"}]'
output_dotenv_generate "test" "dev" "$outfile3" "$secrets_json3"
line3=$(sed -n '3p' "$outfile3")
assert_eq "hyphen to underscore" "MY_API_KEY=val123" "$line3"

# Test 6: input validation
echo "Test 6: input validation"
assert_exit_code "empty project" 1 output_dotenv_generate "" "sit" "$outfile" "$secrets_json"
assert_exit_code "empty environment" 1 output_dotenv_generate "proj" "" "$outfile" "$secrets_json"
assert_exit_code "empty output_file" 1 output_dotenv_generate "proj" "sit" "" "$secrets_json"
assert_exit_code "empty secrets_json" 1 output_dotenv_generate "proj" "sit" "$outfile" ""

# Test 7: creates output directory if needed
echo "Test 7: creates output directory"
nested_outfile="$TMPDIR_TEST/nested/dir/.env.test"
output_dotenv_generate "test" "dev" "$nested_outfile" "$secrets_json"
assert_eq "nested file exists" "true" "$([ -f "$nested_outfile" ] && echo true || echo false)"

# Test 8: values with special characters are quoted
echo "Test 8: special characters"
outfile4="$TMPDIR_TEST/.env.special"
secrets_json4='[{"name":"pass","value":"p@ss$word!"},{"name":"plain","value":"simple"}]'
output_dotenv_generate "test" "dev" "$outfile4" "$secrets_json4"
line3=$(sed -n '3p' "$outfile4")
# Should be quoted due to special chars
assert_eq "special chars quoted" 'PASS="p@ss$word!"' "$line3"
line4=$(sed -n '4p' "$outfile4")
assert_eq "plain unquoted" "PLAIN=simple" "$line4"

echo ""
echo "=== Results: $PASS passed, $FAIL failed ==="

if [[ "$FAIL" -gt 0 ]]; then
    exit 1
fi
