#!/usr/bin/env bash
# Dotenv (.env) output generator for secrets-bridge.
# Generates .env files from secret values.

# Resolve the directory this script lives in
_DOTENV_OUTPUT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Generate a dotenv file.
#
# Arguments:
#   $1 - project name (unused in dotenv format but kept for API consistency)
#   $2 - environment name
#   $3 - output file path
#   $4 - JSON array of secret entries: [{"name":"x","value":"y"}, ...]
#
# Output format:
#   # Generated by secrets-bridge - do not edit
#   # Environment: sit
#   KEY1=value1
#   KEY2="value with spaces"
#
# Values containing spaces, quotes, or shell special characters are double-quoted.
output_dotenv_generate() {
    local project="$1" environment="$2" output_file="$3" secrets_json="$4"

    [[ -z "$project" ]] && { echo "Error: project name required" >&2; return 1; }
    [[ -z "$environment" ]] && { echo "Error: environment name required" >&2; return 1; }
    [[ -z "$output_file" ]] && { echo "Error: output file path required" >&2; return 1; }
    [[ -z "$secrets_json" ]] && { echo "Error: secrets JSON required" >&2; return 1; }

    # Ensure output directory exists
    local output_dir
    output_dir="$(dirname "$output_file")"
    mkdir -p "$output_dir"

    # Generate the dotenv content
    {
        echo "# Generated by secrets-bridge - do not edit"
        echo "# Environment: $environment"
        echo "$secrets_json" | python3 "$_DOTENV_OUTPUT_DIR/dotenv_helper.py"
    } > "$output_file"
}
